### ISSUE TITLE
Get incoming url list for a certain url

### ISSUE THREAD

**Issue by RioMichael** [shensjw/LSPT-LinkAnalysis#2]
Currently, there is no direct way to get a list of incoming URLs for a certain URL. Should we add a function to accomplish that? Or maybe add a structure similar to adj_matrix but for incoming URLs instead of outgoing URLs? (Currently, I may have to loop through all the nodes to check if the current URL is a child of the node.) Having a way to get that incoming URLs would be really useful when we do the rank update.

**Comment by shensjw** [comment]
If you only want the list of incoming links for a certain node, I can have a vector storing that info under the node class for each node.

**Comment by RioMichael** [comment]
@shensjw If you could add that, that will be perfect :)

**Comment by shensjw** [comment]
Added.
Supposedly, you only need to call functions in Webgraph class to get all the information you need.
